// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjLpWOjRchjjMAY-0XJmGElmJ2gPdHtoU',
    appId: '1:965639261864:web:65cad1e17f4abe0d1fbc9d',
    messagingSenderId: '965639261864',
    projectId: 'money-app-74c57',
    authDomain: 'money-app-74c57.firebaseapp.com',
    storageBucket: 'money-app-74c57.firebasestorage.app',
    measurementId: 'G-FZQV5DVDQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-AJAG8g5sm0u52oM0xZil1dQzDwFY6Rw',
    appId: '1:965639261864:android:58fbd370b8b2b78e1fbc9d',
    messagingSenderId: '965639261864',
    projectId: 'money-app-74c57',
    storageBucket: 'money-app-74c57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNwsRiJQtMw-hJ-B3Z3rQ1wceYP5H54RE',
    appId: '1:965639261864:ios:e763ad6cbb171e661fbc9d',
    messagingSenderId: '965639261864',
    projectId: 'money-app-74c57',
    storageBucket: 'money-app-74c57.firebasestorage.app',
    iosClientId: '965639261864-5ghqoe3eisf04ll6mlb1649rueafh42u.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNwsRiJQtMw-hJ-B3Z3rQ1wceYP5H54RE',
    appId: '1:965639261864:ios:e763ad6cbb171e661fbc9d',
    messagingSenderId: '965639261864',
    projectId: 'money-app-74c57',
    storageBucket: 'money-app-74c57.firebasestorage.app',
    iosClientId: '965639261864-5ghqoe3eisf04ll6mlb1649rueafh42u.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjLpWOjRchjjMAY-0XJmGElmJ2gPdHtoU',
    appId: '1:965639261864:web:10dfcaf2122549cd1fbc9d',
    messagingSenderId: '965639261864',
    projectId: 'money-app-74c57',
    authDomain: 'money-app-74c57.firebaseapp.com',
    storageBucket: 'money-app-74c57.firebasestorage.app',
    measurementId: 'G-Q2DEZG58FB',
  );
}
